apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# commonLabels:
#   app.xgeeks.org/team: idp_geekathon
#   backstage.io/kubernetes-id: excelsi

namespace: idpkathon-dev
# namespace: excelsi-idp_geekathon-dev

resources:
  - ../../base
  - ingress.yaml

images:
  # ATENTION name = image.name NOT name = spec.containers[0].name
  - name: ghcr.io/xgeeks-geekathon/excelsi
    newTag: v1
  - name: ghcr.io/xgeeks-geekathon/excelsi-datafeeder
    newTag: v1
# replicas:
#   - name: excelsi # the deployment name
#     count: 1
